const ActionType = {
  // Fetch todos
  FETCH_TODO_REQUEST: 'FETCH_TODO_REQUEST',
  FETCH_TODO_SUCCESS: 'FETCH_TODO_SUCCESS',
  FETCH_TODO_FAILURE: 'FETCH_TODO_FAILURE',

  // Add todo
  ADD_TODO_REQUEST: 'ADD_TODO_REQUEST',
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
  ADD_TODO_FAILURE: 'ADD_TODO_FAILURE',

  // Delete todo
  DELETE_TODO_REQUEST: 'DELETE_TODO_REQUEST',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  DELETE_TODO_FAILURE: 'DELETE_TODO_FAILURE',

  // Update todo
  UPDATE_TODO_REQUEST: 'UPDATE_TODO_REQUEST',
  UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
  UPDATE_TODO_FAILURE: 'UPDATE_TODO_FAILURE',
};

export default ActionType;
